### ISSUE TITLE
Database breaks the more users are stored

### ISSUE THREAD

**Issue by joshmoore** [ome/apacheds-docker#28]
from @githilman:

> I have using this repo for build my apacheds docker for running in kubernetes. My problem is the database always break. The more user stored on LDAP the more often the data break. I have implement backup and secured all my user but the break is too often. Maybe anyone have a tweak for this issue.

Migrated from #27

**Comment by joshmoore** [comment]
@githilman: can you provide more details on what breaks?

**Comment by githilman** [comment]
actually the data from /var/lib/apacheds

I have keycloak for SSO and using the LDAP to store data. From keycloak when it break it show this log 

`07:40:46,281 ERROR [org.keycloak.storage.ldap.idm.store.ldap.LDAPOperationManager] (default task-21290) Could not query server using DN [ou=system] and filter [(&(mail=susisnt23@gmail.com)(objectclass=inetOrgPerson)(objectclass=organizationalPerson))]: javax.naming.NamingException: [LDAP: error code 80 - OTHER: failed for MessageType : SEARCH_REQUEST
Message ID : 328
    SearchRequest
        baseDn : 'ou=system'
        filter : '(&(mail=mail@gmail.com:[∞])(objectClass=inetOrgPerson:[3873])(objectClass=organizationalPerson:[3873]))'
        scope : single level
        typesOnly : false
        Size Limit : no limit
        Time Limit : no limit
        Deref Aliases : deref Always
        attributes : 'entryUUID', 'uid', 'mail', 'initials', 'sn', 'cn', 'objectclass', 'createTimestamp', 'modifyTimestamp'
org.apache.directory.api.ldap.model.message.SearchRequestImpl@88327c7e    ManageDsaITImpl Control
        Type OID    : '2.16.840.1.113730.3.4.2'
        Criticality : 'false'
`

I can't search the user from the keycloak and can't register any. I do backup for all user so when it breaks I can import all user from ldif file. I delete the file from /var/lib/apacheds in the PVC with another image with repair script. The Apacheds will start again. But since the user increase this issue happen a lot. My backup scheme seem overwhelmed.

For the ApacheDS it not showing any error logs. I try to add log visibility with DEBUG but it show nothing.

**Comment by githilman** [comment]
I see this issue when the memory consumption over the Max Heap size. The memory consumption keep increase by the time. Is there any way to prevent the memory usage increase? I see in my kubernetes workload it increase 100MiB per day and when it hit the max Heap most of entry in LDAP gone. In the last case I have 5000 entries and when this issue happen only 5 entries remaining.

**Comment by joshmoore** [comment]
Hi @githilman. It sounds like you are beyond anything we've tried! We use ApacheDS almost exclusively for testing purposes. It sounds like you will need to either contact the ApacheDS developers directly, or use a different solution.

Sorry I can't be of more help. Good luck!
~Josh

**Comment by githilman** [comment]
Hi @joshmoore  I found my solution for this specific issue. Database breaks after the server got hit with much invalid credential when passwordPolicies is enabled. I disable passwordPolicies and now no more data breaks. Hope this help someone who encountered same issue.

This issue could be closed, thanks.

**Comment by joshmoore** [comment]
Thanks for letting us know, @githilman !
